apiVersion: batch/v1
kind: Job
metadata:
  name: APP_NAME-APP_VERSION-migration
  labels:
    app: APP_NAME-migration
  namespace: PROJECT_NAME
spec:
  template:
    spec:
      containers:
        - name: APP_NAME-migration
          image: CONTAINER_REGISTRY_URLAPP_NAME:APP_VERSION
          command: ["/app/APP_NAME-migration"]
          env:
            - name: APP_ENVIRONMENT
              value: "VAR_APP_ENV"
          resources:
            requests:
              memory: "16Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "2"
      restartPolicy: Never
  # ttlSecondsAfterFinished: 3600
  backoffLimit: 1
