apiVersion: v1
kind: Namespace
metadata:
  labels:
    app: pulstats
  name: manupulse
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app: pulstats
  name: job-reader
  namespace: manupulse
rules:
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - get
  - watch
  - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app: pulstats
  name: job-reader
  namespace: manupulse
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: job-reader
subjects:
- kind: ServiceAccount
  name: default
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: pulstats
  name: pulstats
  namespace: manupulse
spec:
  ports:
  - port: 8000
  selector:
    app: pulstats
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    linkerd.io/inject: enabled
  labels:
    app: pulstats
  name: pulstats
  namespace: manupulse
spec:
  replicas: 3
  selector:
    matchLabels:
      app: pulstats
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
      labels:
        app: pulstats
        namespace: manupulse
    spec:
      containers:
      - env:
        - name: APP_ENVIRONMENT
          value: prod
        image: registry4manupulse.azurecr.io/pulstats:v0.1.61
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8000
          initialDelaySeconds: 3
          periodSeconds: 10
        name: pulstats
        ports:
        - containerPort: 8000
        resources:
          limits:
            cpu: "2"
            memory: 128Mi
          requests:
            cpu: 250m
            memory: 16Mi
      initContainers:
      - args:
        - job
        - pulstats-v0.1.61-migration
        - -n manupulse
        image: groundnuty/k8s-wait-for:v1.5.1
        name: wait-for-pulstats-migration
---
apiVersion: batch/v1
kind: Job
metadata:
  labels:
    app: pulstats
  name: pulstats-v0.1.61-migration
  namespace: manupulse
spec:
  backoffLimit: 1
  template:
    metadata:
      labels:
        app: pulstats
    spec:
      containers:
      - command:
        - /app/pulstats-migration
        env:
        - name: APP_ENVIRONMENT
          value: prod
        image: registry4manupulse.azurecr.io/pulstats:v0.1.61
        name: pulstats-migration
        resources:
          limits:
            cpu: "2"
            memory: 128Mi
          requests:
            cpu: 250m
            memory: 16Mi
      restartPolicy: Never
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/enable-opentracing: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    zipkin-collector-host: collector.linkerd-jaeger
  labels:
    app: pulstats
  name: pulstats-healthcheck
  namespace: manupulse
spec:
  rules:
  - host: manupulse.southeastasia.cloudapp.azure.com
    http:
      paths:
      - backend:
          service:
            name: pulstats
            port:
              number: 8000
        path: /healthz
        pathType: Exact
  tls:
  - hosts:
    - manupulse.southeastasia.cloudapp.azure.com
    secretName: manupulse-southeastasia-cloudapp-azure-com
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/auth-realm: Authentication Required
    nginx.ingress.kubernetes.io/auth-secret: basic-auth-manu
    nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/enable-opentracing: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    zipkin-collector-host: collector.linkerd-jaeger
  labels:
    app: pulstats
  name: pulstats-manu
  namespace: manupulse
spec:
  rules:
  - host: manupulse.southeastasia.cloudapp.azure.com
    http:
      paths:
      - backend:
          service:
            name: pulstats
            port:
              number: 8000
        path: /pulstats/stats
        pathType: Exact
      - backend:
          service:
            name: pulstats
            port:
              number: 8000
        path: /pulstats/health_data
        pathType: Exact
      - backend:
          service:
            name: pulstats
            port:
              number: 8000
        path: /manu/user_session
        pathType: Exact
  tls:
  - hosts:
    - manupulse.southeastasia.cloudapp.azure.com
    secretName: manupulse-southeastasia-cloudapp-azure-com
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/auth-realm: Authentication Required
    nginx.ingress.kubernetes.io/auth-secret: basic-auth-pulse
    nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/enable-opentracing: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    zipkin-collector-host: collector.linkerd-jaeger
  labels:
    app: pulstats
  name: pulstats-pulse
  namespace: manupulse
spec:
  rules:
  - host: manupulse.southeastasia.cloudapp.azure.com
    http:
      paths:
      - backend:
          service:
            name: pulstats
            port:
              number: 8000
        path: /pulse/user_session
        pathType: Exact
  tls:
  - hosts:
    - manupulse.southeastasia.cloudapp.azure.com
    secretName: manupulse-southeastasia-cloudapp-azure-com
